version: '3'
services:

  pg_quarkus_dev:
    container_name: pg_quarkus_dev
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always